"use client";
import Link from "next/link";
import {ArrowRight,BookOpen,CheckCircle2,Factory,Gauge,GraduationCap,ShieldCheck} from "lucide-react";
import {motion} from "motion/react";
import {credentials,industries} from "@/config/site";
const fade={initial:{opacity:0,y:28},whileInView:{opacity:1,y:0},viewport:{once:true,margin:"-90px"},transition:{duration:.7}};

export function HomeSections(){return <>
<section className="border-y border-cyan-200/10 bg-[#041017] py-20 md:py-28"><div className="container grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><motion.div {...fade}><p className="eyebrow">Why HosH</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] md:text-6xl">Capability in the field. Evidence in every decision.</h2><p className="mt-6 max-w-xl text-base leading-8 text-slate-400">Local teams are supported by experienced leadership, subject-matter expertise, controlled processes and fit-for-purpose inspection technology.</p></motion.div><div className="grid gap-3 sm:grid-cols-2">{[[ShieldCheck,"Integrity","Operate lawfully, communicate facts and protect client information."],[Gauge,"Technical excellence","Competent personnel, validated methods and reliable equipment."],[CheckCircle2,"Traceability","Structured reporting that connects findings to decisions."],[GraduationCap,"Continuous learning","Training and development embedded in the operating model."]].map(([Icon,title,copy],i)=><motion.article {...fade} transition={{duration:.65,delay:i*.08}} key={title as string} className="glass rounded-3xl p-6"><Icon className="size-7 text-cyan-300"/><h3 className="mt-7 text-xl font-medium">{title as string}</h3><p className="mt-3 leading-7 text-slate-400">{copy as string}</p></motion.article>)}</div></div></section>
<section className="py-24 md:py-36"><div className="container"><motion.div {...fade} className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="eyebrow">Industries</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em] md:text-6xl">Built for critical environments.</h2></div><Link href="/industries" className="inline-flex items-center gap-2 text-cyan-200">Explore industries <ArrowRight className="size-4"/></Link></motion.div><div className="mt-12 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{industries.map((name,i)=><motion.article {...fade} transition={{duration:.6,delay:i*.06}} key={name} className="group relative min-h-64 overflow-hidden rounded-3xl border border-cyan-200/15 bg-gradient-to-br from-[#0b2633] to-[#03080c] p-7"><div className="absolute -right-8 -top-8 size-40 rounded-full border border-cyan-200/10 transition duration-700 group-hover:scale-125"/><Factory className="size-7 text-cyan-300"/><p className="mono mt-24 text-xs text-cyan-200/70">IND.{String(i+1).padStart(2,"0")}</p><h3 className="mt-2 text-2xl font-medium">{name}</h3><p className="mt-3 text-sm text-slate-500">Client project photography required</p></motion.article>)}</div></div></section>
<section className="border-y border-cyan-200/10 bg-cyan-300/[.035] py-20"><div className="container grid gap-10 lg:grid-cols-[.9fr_1.1fr]"><motion.div {...fade}><p className="eyebrow">Credentials supplied in company profile</p><h2 className="mt-5 text-4xl font-semibold tracking-[-.04em]">Recognition requires evidence.</h2><p className="mt-5 max-w-lg leading-7 text-slate-400">Current certificates, registration numbers, scope and validity dates must be verified before launch.</p><Link href="/certifications" className="mt-7 inline-flex items-center gap-2 text-cyan-200">Review credentials <ArrowRight className="size-4"/></Link></motion.div><div className="grid gap-3 sm:grid-cols-2">{credentials.slice(0,6).map(name=><div key={name} className="glass rounded-2xl p-5"><div className="flex items-start gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-cyan-300"/><div><p className="font-medium">{name}</p><p className="mono mt-2 text-[11px] uppercase tracking-wider text-amber-300/80">Verification pending</p></div></div></div>)}</div></div></section>
<section className="py-24 md:py-32"><div className="container grid gap-4 lg:grid-cols-2"><motion.div {...fade} className="glass rounded-3xl p-8 md:p-10"><GraduationCap className="size-8 text-cyan-300"/><p className="eyebrow mt-10">Technical training</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Build competence that performs in the field.</h2><p className="mt-5 leading-7 text-slate-400">Lead-auditor, welding, QA/QC and HSE programs drawn from the supplied course catalogue.</p><Link href="/training" className="mt-8 inline-flex rounded-full bg-cyan-300 px-5 py-3 font-semibold text-slate-950">View training</Link></motion.div><motion.div {...fade} className="glass rounded-3xl p-8 md:p-10"><BookOpen className="size-8 text-cyan-300"/><p className="eyebrow mt-10">Technical insights</p><h2 className="mt-4 text-4xl font-semibold tracking-tight">Knowledge that supports better asset decisions.</h2><p className="mt-5 leading-7 text-slate-400">A ready structure for future articles, project updates and technical resources.</p><Link href="/insights" className="mt-8 inline-flex rounded-full border border-cyan-200/20 px-5 py-3 text-cyan-100">Explore insights</Link></motion.div></div></section>
</>}
