import type {InnerPageItem} from "@/components/sections/inner-page";

export type PageContent={eyebrow:string;title:string;intro:string;items:readonly InnerPageItem[]};

export const pages={
  about:{eyebrow:"About HosH",title:"Assurance built for consequential work.",intro:"HosH supports industrial organizations with disciplined inspection, verification and workforce capability. Company history and leadership details will be finalized after client approval.",items:[{code:"ABT.01",title:"Independent thinking",detail:"Clear technical judgment focused on evidence, applicable standards and operational reality."},{code:"ABT.02",title:"Field-first delivery",detail:"Practical collaboration with engineering, fabrication, maintenance and site teams."},{code:"ABT.03",title:"Traceable reporting",detail:"Structured findings designed to support confident, accountable decisions."},{code:"ABT.04",title:"Continuous capability",detail:"Inspection and training services that strengthen both assets and the people responsible for them."}]},
  services:{eyebrow:"Technical Services",title:"Inspection intelligence across the asset lifecycle.",intro:"A modular service portfolio for fabrication, commissioning, operations and maintenance. Exact methods and accreditation claims remain subject to client confirmation.",items:[{code:"NDT.01",title:"Non-Destructive Testing",detail:"Evidence-led examination without compromising the integrity or future use of an asset."},{code:"INS.02",title:"Industrial Inspection",detail:"Field assurance for equipment, fabrication quality and critical site operations."},{code:"CER.03",title:"Certification Support",detail:"Structured verification workflows aligned with applicable codes, standards and project requirements."},{code:"TRN.04",title:"Technical Training",detail:"Practical capability development for inspectors, engineers, technicians and site teams."}]},
  industries:{eyebrow:"Industries",title:"Technical confidence in demanding environments.",intro:"HosH is being positioned to support high-consequence sectors where asset integrity, traceability and competent personnel matter most.",items:[{code:"IND.01",title:"Oil & Gas",detail:"Inspection and assurance support for upstream, midstream and downstream operations."},{code:"IND.02",title:"Power & Energy",detail:"Integrity-focused services for generation assets, plant equipment and supporting infrastructure."},{code:"IND.03",title:"Manufacturing",detail:"Quality verification across fabrication, production systems and engineered components."},{code:"IND.04",title:"Infrastructure",detail:"Technical oversight for industrial construction, facilities and essential assets."}]},
  training:{eyebrow:"Training",title:"Build competence that performs in the field.",intro:"Training experiences will combine technical foundations, practical context and measurable learning outcomes. Course names, schedules and awarding bodies require client confirmation.",items:[{code:"LRN.01",title:"NDT Foundations",detail:"Core principles, method awareness, limitations and safe field application."},{code:"LRN.02",title:"Inspection Practice",detail:"Structured inspection planning, observation, documentation and reporting."},{code:"LRN.03",title:"Codes & Standards",detail:"Guided interpretation of relevant technical requirements and acceptance criteria."},{code:"LRN.04",title:"Custom Programs",detail:"Role-specific learning paths shaped around client assets, teams and operational needs."}]},
  certifications:{eyebrow:"Certifications",title:"Verifiable standards. Visible accountability.",intro:"This section will present only verified accreditations, approvals, personnel certifications and standards supplied by the client.",items:[{code:"VER.01",title:"Company Credentials",detail:"A controlled record of approved company registrations, accreditations and authorizations."},{code:"VER.02",title:"Personnel Competence",detail:"Relevant inspector and trainer qualifications presented with clear scope and validity."},{code:"VER.03",title:"Standards Alignment",detail:"Applicable codes and standards mapped accurately to each delivered service."},{code:"VER.04",title:"Document Verification",detail:"A future verification workflow for certificates and controlled assurance documents."}]},
  contact:{eyebrow:"Contact",title:"Bring us the asset, risk or capability challenge.",intro:"Official phone, email, address, WhatsApp and operating regions are awaiting client confirmation. No enquiry form will be activated until its secure delivery destination is approved.",items:[{code:"CON.01",title:"Inspection Enquiries",detail:"Share the asset type, location, required method, project stage and expected schedule."},{code:"CON.02",title:"Training Enquiries",detail:"Include the course topic, participant count, experience level and preferred delivery format."},{code:"CON.03",title:"Documents to Prepare",detail:"Relevant specifications, drawings, standards, scope and available inspection history."},{code:"CON.04",title:"Response Information",detail:"HosH will confirm technical fit, information gaps, availability and the appropriate next step."}]}
} satisfies Record<string,PageContent>;
