export const navigation=[
  {label:"About",href:"/about"},{label:"Services",href:"/services"},{label:"Industries",href:"/industries"},
  {label:"Training",href:"/training"},{label:"Certifications",href:"/certifications"},{label:"Insights",href:"/insights"}
] as const;

export const services=[
  {code:"QA.01",slug:"construction-qa-qc",title:"Construction QA/QC",short:"Supervision and control from approved documentation through project completion.",summary:"HosH deploys competent inspectors to support implementation of project quality systems across oil and gas, petrochemical, power and civil construction.",points:["QA/QC supervision","Inspection test plans","Project quality plans","Civil structure integrity"]},
  {code:"EXP.02",slug:"expediting",title:"Expediting",short:"Proactive vendor follow-up, assessment and timely reporting.",summary:"Technical expediting helps secure the quality and timely delivery of goods, components and project activities.",points:["Vendor coordination","Progress verification","Schedule risk reporting","Pre-shipment follow-up"]},
  {code:"NDT.03",slug:"non-destructive-testing",title:"Non-Destructive Testing",short:"Conventional and advanced examination delivered by qualified personnel.",summary:"A broad NDT portfolio for structural and mechanical components, designed to support safe, reliable and cost-effective operation.",points:["MPI, FMPI and DPT","UFD and UTG","TOFD and phased array","MFL, PMI and digital radiography"]},
  {code:"PIP.04",slug:"pipeline-inspection",title:"Pipeline Inspection",short:"Traceable integrity data from construction through operation.",summary:"Pipeline QC Mapping connects joint-level quality records, locations, inspection evidence and substantiated daily progress.",points:["Pipeline QC mapping","Construction supervision","Integrity assessment","Joint-level traceability"]},
  {code:"LFT.05",slug:"lifting-equipment",title:"Lifting Equipment Certification",short:"Inspection and certification support for lifting and hoisting equipment.",summary:"Inspection programs for cranes, lifts, hoists, slings, accessories and related equipment against applicable requirements.",points:["Cranes and forklifts","Hoists and lifting beams","Slings and accessories","Elevators and cargo lifts"]},
  {code:"TNK.06",slug:"storage-tank-inspection",title:"Storage Tank Inspection",short:"Early detection of deterioration before leakage or failure.",summary:"Integrated tank integrity support using appropriate inspection methods and experienced operators.",points:["MFL floor scanning","Vacuum box testing","Corrosion mapping","Plumbness and UT"]},
  {code:"PV.07",slug:"pressure-vessel-inspection",title:"Boiler & Pressure Vessel",short:"Code-aware inspection and quality-control support.",summary:"Inspection for manufacturers, repair organizations, facility managers and asset owners managing boiler and pressure-vessel integrity.",points:["Code requirement review","Non-intrusive inspection","Quality-system support","Repair and alteration oversight"]},
  {code:"VEN.08",slug:"vendor-evaluation",title:"Vendor Evaluation",short:"Independent capability, system and acceptance assessment.",summary:"Supplier evaluation services focused on competence, compliance, timely reporting and project-specific risk.",points:["Vendor capability audit","Management-system audit","Factory acceptance test","Third-party inspection"]},
  {code:"QMS.09",slug:"qms-audits",title:"QMS Audits & Documentation",short:"Audits and controlled documents that support continual improvement.",summary:"Quality-system audits, recommendations and documentation aligned to the client’s applicable requirements.",points:["Quality manuals","ITPs and PQPs","QC procedures and forms","ISO 9001 support"]},
  {code:"HSE.10",slug:"hse-services",title:"HSE Services",short:"Practical inspection, audit, certification and training support.",summary:"Field-focused HSE services covering lifting operations, work at height, fire, electrical, scaffolding and construction activities.",points:["Workplace HSE audits","Task risk assessment","Construction supervision","Operator competence"]}
] as const;

export const industries=["Oil & Gas","Petrochemical","Power Generation","Industrial Construction","Marine & Offshore","Manufacturing"] as const;
export const credentials=["IMS: ISO 9001 / 14001 / 18001","ISO/IEC 17020","PSQCA Registration","LEEA","American Welding Society","ASTM","ASNT Corporate Partner","ASQ Corporate Member"] as const;
